### ISSUE TITLE
Question about converter compatability

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/capitains_corpora_converter#7]
Hi Thibault, your code works great for us. Thank you.

I am writing to learn what repositories/corpora the tool is currently compatibly with. In the readme, you give `https://github.com/OpenGreekAndLatin/csel-dev.git`. Which others?

Also, I notice the word `-dev` in the above repo. Are there "production" repos for Greek and Latin?

Thanks again, we're getting close to the point of serving all of your wonderful works.

**Comment by PonteIneptique** [comment]
Hi @kylepjohnson .
Technically, it is partially or completely compatible with : 
- https://github.com/PerseusDL/canonical-greekLit [ ~ 35 % ]
- https://github.com/PerseusDL/canonical-latinLit [ ~ 55 % ]
- https://github.com/PerseusDL/canonical-norseLit
- https://github.com/PerseusDL/canonical-angLit/
- https://github.com/PerseusDL/canonical-farsiLit
- https://github.com/OpenGreekAndLatin/patrologia_latina-dev [ In the work ]
- https://github.com/OpenGreekAndLatin/First1KGreek [ Close to 100% ]
- https://github.com/PersDigUMD/PDL

As we discussed, there is still lot to update/convert in the first two. We would be happy to get some help ;)

**Comment by PonteIneptique** [comment]
And dev was just a name given at the beginning. It is too late to change it but it has been long since it is not dev. Just bad naming practice :)

**Comment by PonteIneptique** [comment]
For any of these repo, you can check their status on our CI env : 

http://ci.perseids.org/repo/:owner/:repo -> http://ci.perseids.org/repo/PerseusDL/canonical-greekLit

**Comment by kylepjohnson** [comment]
Thank you! I will share this with the webapp devs and we will begin converting.
